- id: typos
  name: typos
  description: Source code spell checker, binary install
  language: python
  entry: typos
  args: [--write-changes, --force-exclude]
  types: [text]
  stages: [commit, commit-msg, merge-commit, push, manual]

- id: typos-docker
  name: typos
  description: Source code spell checker, Docker image
  language: docker
  entry: typos
  args: [--write-changes, --force-exclude]
  types: [text]
  stages: [commit, commit-msg, merge-commit, push, manual]

- id: typos-src
  name: typos
  description: Source code spell checker, source install
  language: rust
  entry: typos
  args: [--write-changes, --force-exclude]
  types: [text]
  stages: [commit, commit-msg, merge-commit, push, manual]
