name: "typos-action"
author: "Vanessa Sochat"
description: "Run typos to check spelling in GitHub actions"

inputs:
  files:
    description: "Files or patterns to check"
    required: false

  extend_identifiers:
    description: "Comma separated list of extend identifiers, like someone's name"
    required: false

  extend_words:
    description: "Comma separated list of extend words."
    required: false

  isolated:
    description: "Ignore implicit configuration files"
    required: false
    default: false

  write_changes:
    description: "Write changes to the repository"
    required: false
    default: false

  force_exclude:
    description: "Force exclude of files or patterns"
    required: false
    default: false

  config:
    description: "Use a custom config file."
    required: false

runs:
  using: 'composite'
  steps:
    - id: typos
      run: $GITHUB_ACTION_PATH/action/entrypoint.sh
      shell: bash
      env:
        INSTALL_DIR: .
        INPUT_FILES: ${{ inputs.files }}
        INPUT_EXTEND_IDENTIFIERS: ${{ inputs.extend_identifiers }}
        INPUT_EXTEND_WORDS: ${{ inputs.extend_words }}
        INPUT_ISOLATED: ${{ inputs.isolated }}
        INPUT_WRITE_CHANGES: ${{ inputs.write_changes }}
        INPUT_FORCE_EXCLUDE: ${{ inputs.force_exclude }}
        INPUT_CONFIG: ${{ inputs.config }}

branding:
  icon: "link"
  color: "blue"
