name: "False positive: valid word"
description: A valid english word is being corrected
labels: 'S-triage,A-dict'
body:
  - type: checkboxes
    attributes:
      label: Please complete the following tasks
      options:
        - label: I have searched the [open](https://github.com/crate-ci/typos/issues?q=is%3Aissue%20state%3Aopen%20label%3AA-dict) and [rejected](https://github.com/crate-ci/typos/issues?q=is%3Aissue%20state%3Aclosed%20label%3AA-dict) issues
          required: true
  - type: input
    attributes:
      label: Valid word
    validations:
      required: true
  - type: input
    attributes:
      label: Incorrect correction
    validations:
      required: true
  - type: textarea
    attributes:
      label: Justification
      description: Dictionaries, google trends, google ngram, etc
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notes
      description: Any other relevant information
    validations:
      required: false
